# Site identity
lang: en
permalink: pretty

# Personal details
title: Satvik Tripathi
tagline: "Bridging medical imaging, machine learning, and clinical impact"
role: "Researcher in medical AI and imaging"
email: "Satvikt (at) upenn.edu"
location: "Philadelphia, PA & Boston, MA"
description: "Satvik Tripathi's personal research website focusing on medical imaging, machine learning, and clinical informatics."
keywords: [Satvik Tripathi, radiology, medical imaging, artificial intelligence, Penn Medicine, Harvard Medical School]
canonical: https://satviktri.github.io/
profile_image: /assets/img/profile.jpg
favicon: /assets/img/favicon.png
favicon_dark: /assets/img/favicon-dark.png

# Affiliations and links
affiliations:
  - name: Perelman School of Medicine, University of Pennsylvania
    url: https://www.pennmedicine.org/departments-and-centers/radiology
  - name: Department of Radiology, Harvard Medical School / MGH Martinos Center
    url: https://www.massgeneral.org/imaging/research/martinos

social_links:
  - label: Curriculum Vitae
    url: /assets/files/curriculum_vitae.pdf
  - label: LinkedIn
    url: https://www.linkedin.com/in/satvik-tripathi/
  - label: Google Scholar
    url: https://scholar.google.com/
  - label: X (Twitter)
    url: https://x.com/Satvikt_ai
  - label: Email
    url: mailto:Satvikt@upenn.edu

# Analytics
google_analytics: G-V08WLNR7E2

# Build settings
markdown: kramdown
theme: null
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - html_source_file/
