# Site identity
lang: en
permalink: pretty

# Personal details
title: Satvik Tripathi
tagline: "Clinically Relevant AI for Radiology, Oncology, and Global Health"
role: "Researcher"
description: "Satvik Tripathi's personal research website."
keywords: [Satvik Tripathi, radiology, medical imaging, artificial intelligence, Penn Medicine, Harvard Medical School]
canonical: https://satviktri.github.io/
profile_image: /assets/img/profile.jpg
favicon: /assets/img/favicon.png
favicon_dark: /assets/img/favicon-dark.png

# Affiliations and links
affiliations:
  - name: Perelman School of Medicine, University of Pennsylvania
    url: https://www3.pennmedicine.org/departments-and-centers/department-of-radiology
  - name: Martinos Center, Mass General Hospital, Harvard Medical School
    url: https://www.martinos.org/

social_links:
  - label: Curriculum Vitae
    url: /assets/files/curriculum_vitae.pdf
  - label: LinkedIn
    url: https://www.linkedin.com/in/satvik-tripathi/
  - label: Google Scholar
    url: https://scholar.google.com/citations?user=d-8xB2sAAAAJ&hl=en
  - label: X (Twitter)
    url: https://x.com/Satvikt_ai
  - label: Email
    url: mailto:Satvikt@upenn.edu

# Analytics
google_analytics: G-V08WLNR7E2

# Build settings
markdown: kramdown
theme: null
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - html_source_file/
